[package]
name = "meatballs-live-services-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.3"
prost = "0.11"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.8"
tonic-web = "0.4.0"

[build-dependencies]
tonic-build = "0.8"
